# Generated by Django 3.2 on 2023-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_alter_program_abb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='access_token',
        ),
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
