# Generated by Django 3.2 on 2023-09-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20230928_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='acadmicYear',
            new_name='acadamicyear',
        ),
    ]
