# Generated by Django 3.2 on 2023-09-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_rename_acadamicyear_fee_academicyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarytransaction',
            old_name='academicYear',
            new_name='acadamicyear',
        ),
    ]
