# Generated by Django 3.2 on 2023-09-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_rename_academicyear_librarytransaction_acadamicyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarytransaction',
            old_name='acadamicyear',
            new_name='academicyear',
        ),
    ]
