# Generated by Django 3.2 on 2023-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_rename_acadamicyear_librarytransaction_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
